import React, { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Speech from 'expo-speech';
import { Screen } from '@/components/Screen';
import { PageHeader } from '@/components/PageHeader';
import { AppCard } from '@/components/AppCard';
import { findWords } from '@/utils/vocabulary';
import { colors } from '@/theme/colors';

export default function Dictionary(){const[q,setQ]=useState('');const results=useMemo(()=>q.trim().length?findWords(q,undefined,null,30):[],[q]);return <Screen><PageHeader title="Từ điển" subtitle="English → Vietnamese • dữ liệu offline"/><View style={styles.search}><Ionicons name="search" size={19} color={colors.textMuted}/><TextInput autoFocus value={q} onChangeText={setQ} placeholder="Nhập từ tiếng Anh..." placeholderTextColor={colors.textMuted} style={styles.input}/></View>{!q.trim()?<View style={styles.empty}><Ionicons name="book-outline" size={42} color={colors.primary}/><Text style={styles.emptyTitle}>Tra cứu từ tiếng Anh</Text><Text style={styles.emptySub}>Tìm theo từ hoặc một phần nghĩa tiếng Việt.</Text></View>:<View style={{gap:9,marginTop:14}}>{results.map(w=><AppCard key={w.id}><View style={styles.row}><View style={{flex:1}}><Text style={styles.term}>{w.term}</Text><Text style={styles.ipa}>{w.ipa||w.pronunciation||''} • {w.partOfSpeech||'word'}</Text><Text style={styles.meaning}>{w.translation}</Text>{w.exampleSentence?<Text style={styles.example}>{w.exampleSentence}</Text>:null}</View><Pressable style={styles.sound} onPress={()=>Speech.speak(w.term,{language:'en-US'})}><Ionicons name="volume-high-outline" size={20} color={colors.primary}/></Pressable></View></AppCard>)}{!results.length&&<Text style={styles.noResult}>Không tìm thấy từ phù hợp.</Text>}</View>}</Screen>}
const styles=StyleSheet.create({search:{height:50,borderRadius:15,backgroundColor:colors.white,borderWidth:1,borderColor:colors.borderStrong,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:14},input:{flex:1,fontSize:15,color:colors.text},empty:{alignItems:'center',paddingTop:90,gap:9},emptyTitle:{fontSize:18,fontWeight:'900',color:colors.text},emptySub:{fontSize:12.5,color:colors.textSecondary},row:{flexDirection:'row',alignItems:'flex-start',gap:10},term:{fontSize:19,fontWeight:'900',color:colors.text},ipa:{fontSize:11.5,color:colors.textMuted,marginTop:2},meaning:{fontSize:14,color:colors.text,marginTop:7},example:{fontSize:12.5,color:colors.textSecondary,fontStyle:'italic',marginTop:7,lineHeight:18},sound:{width:40,height:40,borderRadius:12,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},noResult:{textAlign:'center',color:colors.textMuted,marginTop:30}});
