import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen';
import { AppButton } from '@/components/Buttons';
import { HustLogo } from '@/components/HustLogo';
import { useAuth } from '@/contexts/AuthContext';
import { colors } from '@/theme/colors';

function Chips({items,value,onChange}:{items:string[];value:string;onChange:(v:string)=>void}){return <View style={styles.chips}>{items.map(x=><Pressable key={x} onPress={()=>onChange(x)} style={[styles.chip,value===x&&styles.chipOn]}><Text style={[styles.chipText,value===x&&styles.chipTextOn]}>{x}</Text></Pressable>)}</View>}
export default function Onboarding(){const {updateProfile}=useAuth();const[level,setLevel]=useState('A1');const[goal,setGoal]=useState('Giao tiếp');const[minutes,setMinutes]=useState('15');const[loading,setLoading]=useState(false);async function save(){try{setLoading(true);await updateProfile({englishLevel:level,learningGoal:goal,dailyMinutes:Number(minutes)});router.replace('/(tabs)/home')}catch(e:any){Alert.alert('Chưa lưu được',e?.message||'Vui lòng thử lại.')}finally{setLoading(false)}}return <Screen contentStyle={styles.page}><HustLogo size={56}/><View><Text style={styles.title}>Thiết lập lộ trình của bạn</Text><Text style={styles.sub}>Bạn có thể thay đổi các lựa chọn này sau trong hồ sơ.</Text></View><View style={styles.block}><Text style={styles.label}>Trình độ hiện tại</Text><Chips items={['A1','A2','B1','B2','C1','C2']} value={level} onChange={setLevel}/></View><View style={styles.block}><Text style={styles.label}>Mục tiêu</Text><Chips items={['Giao tiếp','TOEIC','IELTS','Học tập','Công việc','Du lịch']} value={goal} onChange={setGoal}/></View><View style={styles.block}><Text style={styles.label}>Thời gian học mỗi ngày</Text><Chips items={['10','15','20','30','45']} value={minutes} onChange={setMinutes}/><Text style={styles.unit}>{minutes} phút/ngày</Text></View><AppButton title="Bắt đầu học" onPress={save} loading={loading} icon="arrow-forward"/></Screen>}
const styles=StyleSheet.create({page:{maxWidth:680,alignSelf:'center',gap:26,paddingTop:30},title:{fontSize:30,fontWeight:'900',color:colors.text,letterSpacing:-.8},sub:{fontSize:14,color:colors.textSecondary,marginTop:7},block:{gap:12},label:{fontSize:16,fontWeight:'800',color:colors.text},chips:{flexDirection:'row',flexWrap:'wrap',gap:9},chip:{borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.white,borderRadius:999,paddingHorizontal:15,paddingVertical:10},chipOn:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{fontWeight:'700',color:colors.textSecondary},chipTextOn:{color:colors.white},unit:{color:colors.primary,fontWeight:'800',marginTop:2}});
