import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/Screen';
import { PageHeader } from '@/components/PageHeader';
import { AppCard } from '@/components/AppCard';
import { useLearning } from '@/contexts/LearningContext';
import { useAuth } from '@/contexts/AuthContext';
import { colors } from '@/theme/colors';

export default function Progress(){const{state,accuracy}=useLearning();const{user}=useAuth();const goal=user?.dailyMinutes||15;const pct=Math.min(100,Math.round(state.minutesToday/goal*100));const stats=[['Từ đã học',state.studiedWordIds.length,'book-outline'],['Từ cần ôn',state.reviewWordIds.length,'refresh-outline'],['Từ đã lưu',state.savedWordIds.length,'bookmark-outline'],['Bài hoàn thành',state.completedLessonIds.length,'checkmark-circle-outline']] as const;return <Screen><PageHeader title="Tiến độ học tập" subtitle="Theo dõi hoạt động English của bạn"/><AppCard style={styles.hero}><Text style={styles.kicker}>MỤC TIÊU HÔM NAY</Text><Text style={styles.big}>{state.minutesToday} / {goal} phút</Text><View style={styles.track}><View style={[styles.fill,{width:`${pct}%`} as any]}/></View><Text style={styles.pct}>{pct}% hoàn thành</Text></AppCard><View style={styles.grid}>{stats.map(([label,value,icon])=><AppCard key={label} style={styles.stat}><Ionicons name={icon} size={22} color={colors.primary}/><Text style={styles.num}>{value}</Text><Text style={styles.label}>{label}</Text></AppCard>)}</View><AppCard><Text style={styles.section}>Độ chính xác</Text><Text style={styles.accuracy}>{accuracy}%</Text><Text style={styles.desc}>{state.totalAnswers?`${state.correctAnswers}/${state.totalAnswers} câu trả lời đúng.`:'Hãy làm quiz để bắt đầu có thống kê.'}</Text></AppCard></Screen>}
const styles=StyleSheet.create({hero:{backgroundColor:colors.primary,marginBottom:12},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#FFDDE4'},big:{fontSize:30,fontWeight:'900',color:colors.white,marginTop:7},track:{height:9,backgroundColor:'rgba(255,255,255,.2)',borderRadius:99,overflow:'hidden',marginTop:15},fill:{height:'100%',backgroundColor:colors.white,borderRadius:99},pct:{fontSize:11,color:'#FFE8ED',marginTop:8},grid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:9,marginBottom:12},stat:{width:'48.5%'},num:{fontSize:24,fontWeight:'900',color:colors.text,marginTop:8},label:{fontSize:11.5,color:colors.textSecondary,marginTop:2},section:{fontSize:16,fontWeight:'900',color:colors.text},accuracy:{fontSize:44,fontWeight:'900',color:colors.primary,marginTop:6},desc:{fontSize:12.5,color:colors.textSecondary,marginTop:3}});
