import React, { useState } from 'react';
import { Alert, StyleSheet, Switch, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { PageHeader } from '@/components/PageHeader';
import { AppCard } from '@/components/AppCard';
import { AppButton } from '@/components/Buttons';
import { useAuth } from '@/contexts/AuthContext';
import { colors } from '@/theme/colors';

export default function Settings(){const{user,updateProfile}=useAuth();const[sound,setSound]=useState(true);const[autoPronounce,setAutoPronounce]=useState(true);const[notifications,setNotifications]=useState(false);const[minutes,setMinutes]=useState(user?.dailyMinutes||15);async function save(){await updateProfile({dailyMinutes:minutes});Alert.alert('Đã lưu','Cài đặt học tập đã được cập nhật.')}return <Screen contentStyle={styles.page}><PageHeader title="Cài đặt" subtitle="HustLingo English only"/><AppCard><Setting title="Âm thanh" subtitle="Bật âm thanh trong bài học" value={sound} onChange={setSound}/><Setting title="Tự động phát âm" subtitle="Phát từ khi mở flashcard" value={autoPronounce} onChange={setAutoPronounce}/><Setting title="Thông báo học tập" subtitle="Bật/tắt tùy chọn nhắc học trong ứng dụng" value={notifications} onChange={setNotifications} last/></AppCard><Text style={styles.section}>Mục tiêu mỗi ngày</Text><View style={styles.minutes}>{[10,15,20,30,45].map(x=><Text key={x} onPress={()=>setMinutes(x)} style={[styles.minute,minutes===x&&styles.minuteOn]}>{x}m</Text>)}</View><Text style={styles.note}>Ngôn ngữ học được cố định là English để trải nghiệm học tập nhất quán.</Text><AppButton title="Lưu cài đặt" onPress={save}/></Screen>}
function Setting({title,subtitle,value,onChange,last}:{title:string;subtitle:string;value:boolean;onChange:(v:boolean)=>void;last?:boolean}){return <View style={[styles.setting,!last&&styles.border]}><View style={{flex:1}}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingSub}>{subtitle}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{true:colors.primaryLight,false:'#D7D9DE'}} thumbColor={value?colors.primary:colors.white}/></View>}
const styles=StyleSheet.create({page:{maxWidth:700,alignSelf:'center'},setting:{minHeight:67,flexDirection:'row',alignItems:'center',gap:12},border:{borderBottomWidth:1,borderBottomColor:colors.border},settingTitle:{fontSize:14,fontWeight:'800',color:colors.text},settingSub:{fontSize:11.5,color:colors.textSecondary,marginTop:3},section:{fontSize:16,fontWeight:'900',color:colors.text,marginTop:23,marginBottom:10},minutes:{flexDirection:'row',gap:7,marginBottom:15},minute:{flex:1,textAlign:'center',paddingVertical:11,borderRadius:12,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,fontWeight:'800',color:colors.textSecondary},minuteOn:{backgroundColor:colors.primary,color:colors.white,borderColor:colors.primary},note:{fontSize:11.5,lineHeight:18,color:colors.textMuted,marginBottom:18}});
