-- HustLingo Supabase schema
-- Run with: supabase db push (after `supabase link`) or paste into Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default 'HustLingo Learner',
  avatar_url text,
  role text not null default 'learner' check (role in ('learner', 'admin')),
  status text not null default 'active' check (status in ('active', 'disabled')),
  english_level text default 'A1',
  learning_goal text default 'Giao tiếp',
  daily_minutes integer default 15 check (daily_minutes is null or daily_minutes between 5 and 240),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.learning_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{"studiedWordIds":[],"reviewWordIds":[],"savedWordIds":[],"completedLessonIds":[],"correctAnswers":0,"totalAnswers":0,"minutesToday":0}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  message text not null check (char_length(message) between 5 and 2000),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    display_name,
    avatar_url
  ) values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'display_name',
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(coalesce(new.email, 'HustLingo Learner'), '@', 1),
      'HustLingo Learner'
    ),
    coalesce(
      new.raw_user_meta_data ->> 'avatar_url',
      new.raw_user_meta_data ->> 'picture'
    )
  )
  on conflict (id) do update set
    email = excluded.email,
    display_name = case
      when public.profiles.display_name = 'HustLingo Learner' then excluded.display_name
      else public.profiles.display_name
    end,
    avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url),
    updated_at = now();

  insert into public.learning_progress (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.learning_progress enable row level security;
alter table public.feedback enable row level security;

-- Re-create policies safely when migration is re-run manually.
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "progress_select_own" on public.learning_progress;
drop policy if exists "progress_insert_own" on public.learning_progress;
drop policy if exists "progress_update_own" on public.learning_progress;
drop policy if exists "feedback_insert_own" on public.feedback;

create policy "profiles_select_own"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

create policy "profiles_update_own"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "progress_select_own"
on public.learning_progress for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "progress_insert_own"
on public.learning_progress for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "progress_update_own"
on public.learning_progress for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "feedback_insert_own"
on public.feedback for insert
to authenticated
with check ((select auth.uid()) = user_id);

revoke all on table public.profiles from anon;
revoke all on table public.learning_progress from anon;
revoke all on table public.feedback from anon;

grant select, insert, update on table public.profiles to authenticated;
grant select, insert, update on table public.learning_progress to authenticated;
grant insert on table public.feedback to authenticated;
